SELECT CONCAT('/home/grep/src/', board.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD as board, USED_GOODS_FILE as file
where board.BOARD_ID = file.BOARD_ID and board.VIEWS = (
    SELECT MAX(VIEWS)
    FROM USED_GOODS_BOARD
)
ORDER BY FILE_ID DESC
;
