-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', UF.BOARD_ID, '/', UF.FILE_ID, UF.FILE_NAME, UF.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD UG
JOIN USED_GOODS_FILE UF ON UG.BOARD_ID = UF.BOARD_ID
WHERE UG.BOARD_ID = (
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD
    WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
    LIMIT 1
)
ORDER BY UF.FILE_ID DESC
