SELECT 
    MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM 
    MEMBER_PROFILE m JOIN REST_REVIEW r ON m.MEMBER_ID=r.MEMBER_ID
WHERE
    MEMBER_NAME IN 
    (
        SELECT 
        m.MEMBER_NAME
    FROM 
        MEMBER_PROFILE m JOIN REST_REVIEW r ON m.MEMBER_ID=r.MEMBER_ID
    GROUP BY 
        m.MEMBER_NAME
    HAVING
        COUNT(*) = (
        SELECT 
            COUNT(*)
        FROM 
            MEMBER_PROFILE m JOIN REST_REVIEW r ON m.MEMBER_ID=r.MEMBER_ID
        GROUP BY m.MEMBER_NAME
        ORDER BY COUNT(*) DESC
        LIMIT 1
        )
    )
ORDER BY REVIEW_DATE, REVIEW_TEXT
