WITH sub as (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(MEMBER_ID) DESC
    LIMIT 1
)
SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, "%Y-%m-%d") as REVIEW_DATE
FROM MEMBER_PROFILE JOIN REST_REVIEW USING(MEMBER_ID)
WHERE MEMBER_ID = (SELECT MEMBER_ID FROM sub)
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC
