SELECT 
    YEAR(o.SALES_DATE) AS YEAR, 
    MONTH(o.SALES_DATE) AS MONTH, 
    COUNT(DISTINCT u.USER_ID) AS PURCHASED_USERS,
    ROUND(
        COUNT(DISTINCT u.USER_ID) / 
        (SELECT COUNT(DISTINCT USER_ID) 
         FROM USER_INFO 
         WHERE YEAR(JOINED) = 2021), 1) 
    AS PURCHASED_RATIO
FROM 
    USER_INFO u 
JOIN 
    ONLINE_SALE o 
    ON u.USER_ID = o.USER_ID
WHERE 
    YEAR(u.JOINED) = 2021 
    AND o.SALES_AMOUNT > 0
GROUP BY 
    YEAR(o.SALES_DATE), MONTH(o.SALES_DATE)
ORDER BY 
    YEAR(o.SALES_DATE), MONTH(o.SALES_DATE);
